version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "80:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - manticoresearch  

  web:
    build: ./client/my-app
    ports:
      - "3000:3000"
    volumes:
      - ./client/my-app:/user/src/app
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  manticoresearch:
    container_name: manticore-search-semantic
    image: manticoresearch/manticore:6.3.6
    environment:
      - EXTRA=1
    ports:
      - "9306:9306" 
      - "9312:9312" 
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./manticore-data:/var/lib/manticore 


  python-app:
    container_name: embedding_generator
    build:
      context: . 
      dockerfile: Dockerfile 
    volumes:
      - ./server:/app  
      - ./data:/app/data  
    depends_on:
      - manticoresearch  
    environment:
      - DATA_PATH=/app/server/data/embeddings_100.csv 
    command: ["python", "/app/server/data_scripts/load_data.py"]  
    tty: true
